import fs from "node:fs";
import path from "node:path";
import { describe, expect, test } from "vitest";
import {
  doctorReasonCatalog,
  formatDoctorReasonDetail,
} from "../src/shared/doctor/doctor-reasons";

function read(filePath: string): string {
  return fs.readFileSync(path.resolve(process.cwd(), filePath), "utf-8");
}

function extractLiteralReasonCodes(filePath: string): string[] {
  const source = read(filePath);
  return [...source.matchAll(/reasons\.push\("([A-Z0-9_]+)"\)/g)].map((match) => match[1] ?? "");
}

function collectKnownReasonCodes(): string[] {
  const codes = new Set<string>();

  for (const filePath of [
    "src/modules/doctor/doctor.service.ts",
    "src/modules/doctor/inspectors/compile.inspector.ts",
    "src/modules/doctor/inspectors/database.inspector.ts",
  ]) {
    for (const code of extractLiteralReasonCodes(filePath)) {
      codes.add(code);
    }
  }

  const distillationPrefixes = ["VIBE_DISTILLATION", "SOURCE_DISTILLATION"];
  const distillationSuffixes = [
    "LAUNCH_AGENT_NOT_INSTALLED",
    "LAUNCH_AGENT_NOT_LOADED",
    "NEVER_RAN",
    "STALE",
    "QUEUE_STALE_RUNNING",
    "PIPELINE_LOCK_STALE",
    "QUEUE_STOPPED",
  ];
  for (const prefix of distillationPrefixes) {
    for (const suffix of distillationSuffixes) {
      codes.add(`${prefix}_${suffix}`);
    }
  }

  for (const syncStateId of ["codex_logs", "antigravity_logs"]) {
    const upper = syncStateId.toUpperCase();
    codes.add(`${upper}_SYNC_STALE`);
    codes.add(`${upper}_SYNC_WARNINGS`);
  }

  return [...codes].sort();
}

describe("doctor reason catalog", () => {
  test("covers all known reason codes generated by doctor service", () => {
    const knownCodes = collectKnownReasonCodes();
    const missing = knownCodes.filter((code) => !(code in doctorReasonCatalog));

    expect(missing).toEqual([]);
  });

  test("fallback detail is generated for unknown code", () => {
    const detail = formatDoctorReasonDetail("UNMAPPED_CUSTOM_REASON");
    expect(detail.code).toBe("UNMAPPED_CUSTOM_REASON");
    expect(detail.label).toBe("Unmapped Custom Reason");
    expect(detail.description).toBe("Doctor が未定義の診断コードを返しました。");
  });
});
