import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    testTimeout: 30000,
    include: [
      "web/src/**/*.test.ts",
      "web/src/**/*.test.tsx",
      "test/**/*.test.ts",
      "test/**/*.test.tsx",
    ],
    setupFiles: ["test/setup.ts"],
    environmentMatchGlobs: [
      ["test/components/**", "jsdom"],
      ["web/src/**", "jsdom"],
    ],
    globals: true,
    alias: {
      "@": path.resolve(__dirname, "./web/src"),
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: ["src/**/*.ts", "web/src/**/*.{ts,tsx}"],
      exclude: [
        "src/cli/**",
        "src/db/migrations/**",
        "src/db/seed.ts",
        "src/db/sqlite/**",
        "src/db/schema*",
        "src/db/schema.ts",
        "src/db/schema.utils.ts",
        "src/**/*repository*",
        "src/modules/knowledge-portability/import.service.ts",
        "src/modules/knowledge-portability/export.service.ts",
        "src/modules/sqlite-migration/**",
        "src/modules/doctor/inspectors/**",
        "src/modules/settings/settings.service.ts",
        "src/modules/agent-log-sync/sync.service.ts",
        "src/**/*.types.ts",
        "src/modules/queue/core/**",
        "src/modules/landscape/**",
        "src/modules/knowledge/source-linking.service.ts",
        "src/modules/onboarding/**",
        "src/modules/memoryReader/**",
        "src/modules/llm/**",
        "src/index.ts",
        "src/config.ts",
        "src/db/client.ts",
        "src/db/index.ts",
        "src/mcp/registry.ts",

        "src/modules/vibe-memory/**",
        "src/modules/distillation/**",
        "src/modules/distillationTarget/**",
        "src/modules/coverEvidence/**",
        "src/modules/doctor/**",
        "src/modules/graph/**",
        "src/modules/settings/**",
        "src/modules/agent-log-sync/**",
        "src/modules/audit/**",
        "src/modules/codex/**",
        "src/modules/context-decision/**",
        "src/modules/finalize-distill/**",
        "src/modules/findCandidate/**",
        "src/modules/knowledge-portability/**",
        "src/modules/registerCandidate/**",
        "src/modules/knowledge/**",
        "src/modules/embedding/**",
        "src/modules/sources/**",
        "src/modules/context-compiler/**",
        "src/mcp/**",
        "src/shared/schemas/**",
        "src/shared/doctor/**",

        "web/src/**/*.tsx",
        "web/src/lib/**",
        "web/src/admin/components/**",
      ],
    },
  } as any,
});
