#!/bin/bash
set -euo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

PROJECT_ROOT="$(cd -P "$(dirname "$SOURCE")/.." && pwd)"
REMINDER_SCRIPT="$PROJECT_ROOT/scripts/post-commit-candidate-reminder.sh"

LOCAL_MARKER_PRE="memory-router candidate registration pre-commit hook"
LOCAL_MARKER_POST="memory-router candidate registration post-commit hook"
GLOBAL_MARKER_PRE="memory-router global candidate registration pre-commit hook"
GLOBAL_MARKER_POST="memory-router global candidate registration post-commit hook"

GLOBAL_HOOK_DIR="${MEMORY_ROUTER_CANDIDATE_GLOBAL_HOOK_DIR:-$HOME/.config/memory-router/git-hooks}"
GLOBAL_PRE_FILE="$GLOBAL_HOOK_DIR/pre-commit"
GLOBAL_POST_FILE="$GLOBAL_HOOK_DIR/post-commit"

cd "$PROJECT_ROOT"

GIT_DIR="$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -z "$GIT_DIR" ]; then
  echo "not inside a git worktree: $PROJECT_ROOT" >&2
  exit 1
fi
if [[ "$GIT_DIR" != /* ]]; then
  GIT_DIR="$PROJECT_ROOT/$GIT_DIR"
fi

HOOK_DIR="$GIT_DIR/hooks"
LOCAL_PRE_FILE="$HOOK_DIR/pre-commit"
LOCAL_POST_FILE="$HOOK_DIR/post-commit"

is_managed_local_pre() {
  [ -f "$LOCAL_PRE_FILE" ] && grep -q "$LOCAL_MARKER_PRE" "$LOCAL_PRE_FILE"
}

is_managed_local_post() {
  [ -f "$LOCAL_POST_FILE" ] && grep -q "$LOCAL_MARKER_POST" "$LOCAL_POST_FILE"
}

extract_previous_local_pre() {
  if ! is_managed_local_pre; then
    return 0
  fi
  awk -F= '/^MEMORY_ROUTER_PREVIOUS_PRE_COMMIT=/{print $2}' "$LOCAL_PRE_FILE" | tr -d "'\"" | tail -n 1
}

extract_previous_local_post() {
  if ! is_managed_local_post; then
    return 0
  fi
  awk -F= '/^MEMORY_ROUTER_PREVIOUS_POST_COMMIT=/{print $2}' "$LOCAL_POST_FILE" | tr -d "'\"" | tail -n 1
}

write_local_pre() {
  local previous_pre="$1"
  mkdir -p "$HOOK_DIR"
  cat > "$LOCAL_PRE_FILE" <<EOF
#!/bin/sh
# $LOCAL_MARKER_PRE
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_PRE_COMMIT='$previous_pre'

set +e

if [ -n "\$MEMORY_ROUTER_PREVIOUS_PRE_COMMIT" ] && [ -f "\$MEMORY_ROUTER_PREVIOUS_PRE_COMMIT" ]; then
  if [ -x "\$MEMORY_ROUTER_PREVIOUS_PRE_COMMIT" ]; then
    "\$MEMORY_ROUTER_PREVIOUS_PRE_COMMIT" "\$@"
  else
    /bin/sh "\$MEMORY_ROUTER_PREVIOUS_PRE_COMMIT" "\$@"
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="$PROJECT_ROOT" "$REMINDER_SCRIPT" pre-commit
exit 0
EOF
  chmod +x "$LOCAL_PRE_FILE"
}

write_local_post() {
  local previous_post="$1"
  mkdir -p "$HOOK_DIR"
  cat > "$LOCAL_POST_FILE" <<EOF
#!/bin/sh
# $LOCAL_MARKER_POST
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_POST_COMMIT='$previous_post'

set +e

if [ -n "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ] && [ -f "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ]; then
  if [ -x "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ]; then
    "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" "\$@"
  else
    /bin/sh "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" "\$@"
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="$PROJECT_ROOT" "$REMINDER_SCRIPT" post-commit
exit 0
EOF
  chmod +x "$LOCAL_POST_FILE"
}

is_managed_global_pre() {
  [ -f "$GLOBAL_PRE_FILE" ] && grep -q "$GLOBAL_MARKER_PRE" "$GLOBAL_PRE_FILE"
}

is_managed_global_post() {
  [ -f "$GLOBAL_POST_FILE" ] && grep -q "$GLOBAL_MARKER_POST" "$GLOBAL_POST_FILE"
}

extract_previous_global_hooks_path() {
  local file="$1"
  if [ ! -f "$file" ]; then
    return 0
  fi
  awk -F= '/^MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH=/{print $2}' "$file" | tr -d "'\"" | tail -n 1
}

write_global_pre() {
  local previous_hooks_path="$1"
  mkdir -p "$GLOBAL_HOOK_DIR"
  cat > "$GLOBAL_PRE_FILE" <<EOF
#!/bin/sh
# $GLOBAL_MARKER_PRE
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH='$previous_hooks_path'

set +e

REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
GIT_DIR="\$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -n "\$GIT_DIR" ] && [ "\${GIT_DIR#/}" = "\$GIT_DIR" ]; then
  GIT_DIR="\$REPO_ROOT/\$GIT_DIR"
fi

if [ -n "\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH" ]; then
  PREVIOUS_PRE_COMMIT="\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH/pre-commit"
  if [ -f "\$PREVIOUS_PRE_COMMIT" ]; then
    if [ -x "\$PREVIOUS_PRE_COMMIT" ]; then
      "\$PREVIOUS_PRE_COMMIT" "\$@"
    else
      /bin/sh "\$PREVIOUS_PRE_COMMIT" "\$@"
    fi
  fi
fi

if [ -n "\$GIT_DIR" ]; then
  REPO_LOCAL_PRE_COMMIT="\$GIT_DIR/hooks/pre-commit"
  if [ -f "\$REPO_LOCAL_PRE_COMMIT" ] && [ "\$REPO_LOCAL_PRE_COMMIT" != "$GLOBAL_PRE_FILE" ]; then
    if [ -x "\$REPO_LOCAL_PRE_COMMIT" ]; then
      "\$REPO_LOCAL_PRE_COMMIT" "\$@"
    else
      /bin/sh "\$REPO_LOCAL_PRE_COMMIT" "\$@"
    fi
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="\$REPO_ROOT" "$REMINDER_SCRIPT" pre-commit
exit 0
EOF
  chmod +x "$GLOBAL_PRE_FILE"
}

write_global_post() {
  local previous_hooks_path="$1"
  mkdir -p "$GLOBAL_HOOK_DIR"
  cat > "$GLOBAL_POST_FILE" <<EOF
#!/bin/sh
# $GLOBAL_MARKER_POST
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH='$previous_hooks_path'

set +e

REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
GIT_DIR="\$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -n "\$GIT_DIR" ] && [ "\${GIT_DIR#/}" = "\$GIT_DIR" ]; then
  GIT_DIR="\$REPO_ROOT/\$GIT_DIR"
fi

if [ -n "\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH" ]; then
  PREVIOUS_POST_COMMIT="\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH/post-commit"
  if [ -f "\$PREVIOUS_POST_COMMIT" ]; then
    if [ -x "\$PREVIOUS_POST_COMMIT" ]; then
      "\$PREVIOUS_POST_COMMIT" "\$@"
    else
      /bin/sh "\$PREVIOUS_POST_COMMIT" "\$@"
    fi
  fi
fi

if [ -n "\$GIT_DIR" ]; then
  REPO_LOCAL_POST_COMMIT="\$GIT_DIR/hooks/post-commit"
  if [ -f "\$REPO_LOCAL_POST_COMMIT" ] && [ "\$REPO_LOCAL_POST_COMMIT" != "$GLOBAL_POST_FILE" ]; then
    if [ -x "\$REPO_LOCAL_POST_COMMIT" ]; then
      "\$REPO_LOCAL_POST_COMMIT" "\$@"
    else
      /bin/sh "\$REPO_LOCAL_POST_COMMIT" "\$@"
    fi
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="\$REPO_ROOT" "$REMINDER_SCRIPT" post-commit
exit 0
EOF
  chmod +x "$GLOBAL_POST_FILE"
}

install_hook() {
  if [ ! -f "$REMINDER_SCRIPT" ]; then
    echo "missing reminder script: $REMINDER_SCRIPT" >&2
    exit 1
  fi
  chmod +x "$REMINDER_SCRIPT"

  local previous_pre=""
  local previous_post=""

  if is_managed_local_pre; then
    previous_pre="$(extract_previous_local_pre)"
  elif [ -f "$LOCAL_PRE_FILE" ]; then
    previous_pre="$LOCAL_PRE_FILE.memory-router-backup-$(date -u '+%Y%m%dT%H%M%SZ')"
    cp "$LOCAL_PRE_FILE" "$previous_pre"
    chmod +x "$previous_pre" 2>/dev/null || true
    echo "backed up existing pre-commit hook: $previous_pre"
  fi

  if is_managed_local_post; then
    previous_post="$(extract_previous_local_post)"
  elif [ -f "$LOCAL_POST_FILE" ]; then
    previous_post="$LOCAL_POST_FILE.memory-router-backup-$(date -u '+%Y%m%dT%H%M%SZ')"
    cp "$LOCAL_POST_FILE" "$previous_post"
    chmod +x "$previous_post" 2>/dev/null || true
    echo "backed up existing post-commit hook: $previous_post"
  fi

  write_local_pre "$previous_pre"
  write_local_post "$previous_post"
  echo "installed: $LOCAL_PRE_FILE"
  echo "installed: $LOCAL_POST_FILE"
}

uninstall_hook() {
  if is_managed_local_pre; then
    local previous_pre
    previous_pre="$(extract_previous_local_pre)"
    if [ -n "$previous_pre" ] && [ -f "$previous_pre" ]; then
      cp "$previous_pre" "$LOCAL_PRE_FILE"
      chmod +x "$LOCAL_PRE_FILE" 2>/dev/null || true
      echo "restored previous pre-commit hook: $LOCAL_PRE_FILE"
    else
      rm -f "$LOCAL_PRE_FILE"
      echo "removed: $LOCAL_PRE_FILE"
    fi
  else
    echo "not installed: $LOCAL_PRE_FILE"
  fi

  if is_managed_local_post; then
    local previous_post
    previous_post="$(extract_previous_local_post)"
    if [ -n "$previous_post" ] && [ -f "$previous_post" ]; then
      cp "$previous_post" "$LOCAL_POST_FILE"
      chmod +x "$LOCAL_POST_FILE" 2>/dev/null || true
      echo "restored previous post-commit hook: $LOCAL_POST_FILE"
    else
      rm -f "$LOCAL_POST_FILE"
      echo "removed: $LOCAL_POST_FILE"
    fi
  else
    echo "not installed: $LOCAL_POST_FILE"
  fi
}

status_hook() {
  if is_managed_local_pre; then
    echo "installed: $LOCAL_PRE_FILE"
  elif [ -f "$LOCAL_PRE_FILE" ]; then
    echo "unmanaged pre-commit hook exists: $LOCAL_PRE_FILE"
  else
    echo "not installed: $LOCAL_PRE_FILE"
  fi

  if is_managed_local_post; then
    echo "installed: $LOCAL_POST_FILE"
  elif [ -f "$LOCAL_POST_FILE" ]; then
    echo "unmanaged post-commit hook exists: $LOCAL_POST_FILE"
  else
    echo "not installed: $LOCAL_POST_FILE"
  fi
}

run_once() {
  "$REMINDER_SCRIPT" post-commit
}

install_global_hook() {
  if [ ! -f "$REMINDER_SCRIPT" ]; then
    echo "missing reminder script: $REMINDER_SCRIPT" >&2
    exit 1
  fi
  chmod +x "$REMINDER_SCRIPT"

  local current_hooks_path=""
  local previous_hooks_path=""
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ "$current_hooks_path" = "$GLOBAL_HOOK_DIR" ]; then
    if is_managed_global_pre; then
      previous_hooks_path="$(extract_previous_global_hooks_path "$GLOBAL_PRE_FILE")"
    elif is_managed_global_post; then
      previous_hooks_path="$(extract_previous_global_hooks_path "$GLOBAL_POST_FILE")"
    fi
  elif [ -n "$current_hooks_path" ]; then
    previous_hooks_path="$current_hooks_path"
  fi

  write_global_pre "$previous_hooks_path"
  write_global_post "$previous_hooks_path"
  git config --global core.hooksPath "$GLOBAL_HOOK_DIR"
  echo "installed global hooksPath: $GLOBAL_HOOK_DIR"
  if [ -n "$previous_hooks_path" ]; then
    echo "previous global hooksPath will be chained first: $previous_hooks_path"
  fi
}

uninstall_global_hook() {
  local current_hooks_path
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ "$current_hooks_path" != "$GLOBAL_HOOK_DIR" ] && ! is_managed_global_pre && ! is_managed_global_post; then
    echo "global hook not installed by memory-router"
    return 0
  fi

  local previous_hooks_path
  if is_managed_global_pre; then
    previous_hooks_path="$(extract_previous_global_hooks_path "$GLOBAL_PRE_FILE")"
  else
    previous_hooks_path="$(extract_previous_global_hooks_path "$GLOBAL_POST_FILE")"
  fi

  if [ "$current_hooks_path" = "$GLOBAL_HOOK_DIR" ]; then
    if [ -n "$previous_hooks_path" ]; then
      git config --global core.hooksPath "$previous_hooks_path"
      echo "restored global hooksPath: $previous_hooks_path"
    else
      git config --global --unset core.hooksPath || true
      echo "unset global hooksPath"
    fi
  fi

  if is_managed_global_pre; then
    rm -f "$GLOBAL_PRE_FILE"
    echo "removed global hook: $GLOBAL_PRE_FILE"
  fi
  if is_managed_global_post; then
    rm -f "$GLOBAL_POST_FILE"
    echo "removed global hook: $GLOBAL_POST_FILE"
  fi
}

status_global_hook() {
  local current_hooks_path
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ -z "$current_hooks_path" ]; then
    echo "global core.hooksPath: unset"
  else
    echo "global core.hooksPath: $current_hooks_path"
  fi

  if is_managed_global_pre; then
    echo "memory-router global pre-commit hook: installed at $GLOBAL_PRE_FILE"
  else
    echo "memory-router global pre-commit hook: not installed at $GLOBAL_PRE_FILE"
  fi
  if is_managed_global_post; then
    echo "memory-router global post-commit hook: installed at $GLOBAL_POST_FILE"
  else
    echo "memory-router global post-commit hook: not installed at $GLOBAL_POST_FILE"
  fi
}

case "${1:-}" in
  install)
    install_hook
    ;;
  uninstall)
    uninstall_hook
    ;;
  status)
    status_hook
    ;;
  run-once)
    run_once
    ;;
  install-global)
    install_global_hook
    ;;
  uninstall-global)
    uninstall_global_hook
    ;;
  status-global)
    status_global_hook
    ;;
  *)
    echo "Usage: $0 {install|uninstall|status|run-once|install-global|uninstall-global|status-global}"
    exit 1
    ;;
esac
