#!/bin/bash
set -euo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

PROJECT_ROOT="$(cd -P "$(dirname "$SOURCE")/.." && pwd)"
REMINDER_SCRIPT="$PROJECT_ROOT/scripts/post-commit-candidate-reminder.sh"
MANAGED_MARKER="memory-router candidate registration hook"
GLOBAL_MANAGED_MARKER="memory-router global candidate registration hook"
GLOBAL_HOOK_DIR="${MEMORY_ROUTER_CANDIDATE_GLOBAL_HOOK_DIR:-$HOME/.config/memory-router/git-hooks}"
GLOBAL_HOOK_FILE="$GLOBAL_HOOK_DIR/post-commit"

cd "$PROJECT_ROOT"

GIT_DIR="$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -z "$GIT_DIR" ]; then
  echo "not inside a git worktree: $PROJECT_ROOT" >&2
  exit 1
fi
if [[ "$GIT_DIR" != /* ]]; then
  GIT_DIR="$PROJECT_ROOT/$GIT_DIR"
fi

HOOK_DIR="$GIT_DIR/hooks"
HOOK_FILE="$HOOK_DIR/post-commit"

is_managed_hook() {
  [ -f "$HOOK_FILE" ] && grep -q "$MANAGED_MARKER" "$HOOK_FILE"
}

extract_previous_hook() {
  if ! is_managed_hook; then
    return 0
  fi
  awk -F= '/^MEMORY_ROUTER_PREVIOUS_POST_COMMIT=/{print $2}' "$HOOK_FILE" | tr -d "'\"" | tail -n 1
}

write_hook() {
  local previous_hook="$1"
  mkdir -p "$HOOK_DIR"
  cat > "$HOOK_FILE" <<EOF
#!/bin/sh
# $MANAGED_MARKER
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_POST_COMMIT='$previous_hook'

set +e

if [ -n "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ] && [ -f "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ]; then
  if [ -x "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" ]; then
    "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" "\$@"
  else
    /bin/sh "\$MEMORY_ROUTER_PREVIOUS_POST_COMMIT" "\$@"
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="$PROJECT_ROOT" "$REMINDER_SCRIPT" post-commit
exit 0
EOF
  chmod +x "$HOOK_FILE"
}

is_managed_global_hook() {
  [ -f "$GLOBAL_HOOK_FILE" ] && grep -q "$GLOBAL_MANAGED_MARKER" "$GLOBAL_HOOK_FILE"
}

extract_previous_global_hooks_path() {
  if ! is_managed_global_hook; then
    return 0
  fi
  awk -F= '/^MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH=/{print $2}' "$GLOBAL_HOOK_FILE" |
    tr -d "'\"" |
    tail -n 1
}

write_global_hook() {
  local previous_hooks_path="$1"
  mkdir -p "$GLOBAL_HOOK_DIR"
  cat > "$GLOBAL_HOOK_FILE" <<EOF
#!/bin/sh
# $GLOBAL_MANAGED_MARKER
# Generated by scripts/setup-candidate-registration-hook.sh.
MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH='$previous_hooks_path'

set +e

REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
GIT_DIR="\$(git rev-parse --git-dir 2>/dev/null || true)"
if [ -n "\$GIT_DIR" ] && [ "\${GIT_DIR#/}" = "\$GIT_DIR" ]; then
  GIT_DIR="\$REPO_ROOT/\$GIT_DIR"
fi

if [ -n "\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH" ]; then
  PREVIOUS_POST_COMMIT="\$MEMORY_ROUTER_PREVIOUS_GLOBAL_HOOKS_PATH/post-commit"
  if [ -f "\$PREVIOUS_POST_COMMIT" ]; then
    if [ -x "\$PREVIOUS_POST_COMMIT" ]; then
      "\$PREVIOUS_POST_COMMIT" "\$@"
    else
      /bin/sh "\$PREVIOUS_POST_COMMIT" "\$@"
    fi
  fi
fi

if [ -n "\$GIT_DIR" ]; then
  REPO_LOCAL_POST_COMMIT="\$GIT_DIR/hooks/post-commit"
  if [ -f "\$REPO_LOCAL_POST_COMMIT" ] && [ "\$REPO_LOCAL_POST_COMMIT" != "$GLOBAL_HOOK_FILE" ]; then
    if [ -x "\$REPO_LOCAL_POST_COMMIT" ]; then
      "\$REPO_LOCAL_POST_COMMIT" "\$@"
    else
      /bin/sh "\$REPO_LOCAL_POST_COMMIT" "\$@"
    fi
  fi
fi

MEMORY_ROUTER_CANDIDATE_HOOK_REPO_ROOT="\$REPO_ROOT" "$REMINDER_SCRIPT" post-commit
exit 0
EOF
  chmod +x "$GLOBAL_HOOK_FILE"
}

install_hook() {
  if [ ! -f "$REMINDER_SCRIPT" ]; then
    echo "missing reminder script: $REMINDER_SCRIPT" >&2
    exit 1
  fi

  chmod +x "$REMINDER_SCRIPT"

  local previous_hook=""
  if is_managed_hook; then
    previous_hook="$(extract_previous_hook)"
  elif [ -f "$HOOK_FILE" ]; then
    previous_hook="$HOOK_FILE.memory-router-backup-$(date -u '+%Y%m%dT%H%M%SZ')"
    cp "$HOOK_FILE" "$previous_hook"
    chmod +x "$previous_hook" 2>/dev/null || true
    echo "backed up existing post-commit hook: $previous_hook"
  fi

  write_hook "$previous_hook"
  echo "installed: $HOOK_FILE"
}

uninstall_hook() {
  if ! is_managed_hook; then
    echo "not installed: $HOOK_FILE"
    return 0
  fi

  local previous_hook
  previous_hook="$(extract_previous_hook)"
  if [ -n "$previous_hook" ] && [ -f "$previous_hook" ]; then
    cp "$previous_hook" "$HOOK_FILE"
    chmod +x "$HOOK_FILE" 2>/dev/null || true
    echo "restored previous post-commit hook: $HOOK_FILE"
  else
    rm -f "$HOOK_FILE"
    echo "removed: $HOOK_FILE"
  fi
}

status_hook() {
  if is_managed_hook; then
    echo "installed: $HOOK_FILE"
    local previous_hook
    previous_hook="$(extract_previous_hook)"
    if [ -n "$previous_hook" ]; then
      echo "previous hook backup: $previous_hook"
    fi
  elif [ -f "$HOOK_FILE" ]; then
    echo "unmanaged post-commit hook exists: $HOOK_FILE"
  else
    echo "not installed: $HOOK_FILE"
  fi
}

run_once() {
  "$REMINDER_SCRIPT" run-once
}

install_global_hook() {
  if [ ! -f "$REMINDER_SCRIPT" ]; then
    echo "missing reminder script: $REMINDER_SCRIPT" >&2
    exit 1
  fi

  chmod +x "$REMINDER_SCRIPT"

  local current_hooks_path=""
  local previous_hooks_path=""
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ "$current_hooks_path" = "$GLOBAL_HOOK_DIR" ]; then
    previous_hooks_path="$(extract_previous_global_hooks_path)"
  elif [ -n "$current_hooks_path" ]; then
    previous_hooks_path="$current_hooks_path"
  fi

  write_global_hook "$previous_hooks_path"
  git config --global core.hooksPath "$GLOBAL_HOOK_DIR"
  echo "installed global hooksPath: $GLOBAL_HOOK_DIR"
  if [ -n "$previous_hooks_path" ]; then
    echo "previous global hooksPath will be chained first: $previous_hooks_path"
  fi
}

uninstall_global_hook() {
  local current_hooks_path
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ "$current_hooks_path" != "$GLOBAL_HOOK_DIR" ] && ! is_managed_global_hook; then
    echo "global hook not installed by memory-router"
    return 0
  fi

  local previous_hooks_path
  previous_hooks_path="$(extract_previous_global_hooks_path)"
  if [ "$current_hooks_path" = "$GLOBAL_HOOK_DIR" ]; then
    if [ -n "$previous_hooks_path" ]; then
      git config --global core.hooksPath "$previous_hooks_path"
      echo "restored global hooksPath: $previous_hooks_path"
    else
      git config --global --unset core.hooksPath || true
      echo "unset global hooksPath"
    fi
  fi

  if is_managed_global_hook; then
    rm -f "$GLOBAL_HOOK_FILE"
    echo "removed global hook: $GLOBAL_HOOK_FILE"
  fi
}

status_global_hook() {
  local current_hooks_path
  current_hooks_path="$(git config --global --get core.hooksPath || true)"
  if [ -z "$current_hooks_path" ]; then
    echo "global core.hooksPath: unset"
  else
    echo "global core.hooksPath: $current_hooks_path"
  fi

  if is_managed_global_hook; then
    echo "memory-router global hook: installed at $GLOBAL_HOOK_FILE"
    local previous_hooks_path
    previous_hooks_path="$(extract_previous_global_hooks_path)"
    if [ -n "$previous_hooks_path" ]; then
      echo "previous global hooksPath: $previous_hooks_path"
    fi
  else
    echo "memory-router global hook: not installed at $GLOBAL_HOOK_FILE"
  fi
}

case "${1:-}" in
  install)
    install_hook
    ;;
  uninstall)
    uninstall_hook
    ;;
  status)
    status_hook
    ;;
  run-once)
    run_once
    ;;
  install-global)
    install_global_hook
    ;;
  uninstall-global)
    uninstall_global_hook
    ;;
  status-global)
    status_global_hook
    ;;
  *)
    echo "Usage: $0 {install|uninstall|status|run-once|install-global|uninstall-global|status-global}"
    exit 1
    ;;
esac
